version: '2'
services:
    nutask-app:
        image: nutask
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nutask-mysql:3306/nutask?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nutask-mysql:
        extends:
            file: mysql.yml
            service: nutask-mysql
